language: python
python:
  - "2.7"
  - "3.4"
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
script:
  - flake8 .
  - py.test --ds=familyconnect_registration.testsettings */test*.py
