# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-06 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_subscriptionrequest_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionrequest',
            old_name='contact',
            new_name='identity',
        ),
    ]
