# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 12:43
from __future__ import unicode_literals

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models

from ..models import Parish


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        TrigramExtension(),
        migrations.RunSQL(
            'CREATE INDEX "{0}_gin_idx" ON "{0}" USING gin ("{1}" gin_trgm_ops);'.format(Parish._meta.db_table, 'name'),
            reverse_sql='DROP INDEX "{0}_gin_idx" CASCADE;'.format(Parish._meta.db_table)
        ),
    ]
